version: '3.4'

services:
  metinproximityback:
    build:
      context: .
      dockerfile: MetInProximityBack/Dockerfile
    depends_on:
    - cosmos
    - redis
    - sqlEdge

  cosmos:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    container_name: azure_cosmos_db 
    ports:
      - "8081:8081"  # API endpoint
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=3
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1
    restart: always
    volumes:
    - cosmosdb_data:/cosmosdb

  redis:
    image: redis:latest
    container_name: azure_redis
    ports:
      - "6379:6379"  # Redis default port
    restart: always
  
  sqlEdge:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: azure_sql_edge
    ports:
        - "1433:1433"
    restart: always
    volumes: 
        - azure-sql-edge-data:/var/opt/mssql
    environment:
        MSSQL_SA_PASSWORD: "MaxwellState1!"
        ACCEPT_EULA: "Y"

volumes:
    azure-sql-edge-data:
    cosmosdb_data:
